2025-01-31 10:20:53,267 | WARNING | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "C:\Users\vvash\Desktop\Urban University\Lessons_Urban\Module_12\module_12_4_2.py", line 26, in test_run
    runner = module_12_4_1.Runner(123, speed=5)  # Передаем что-то кроме строки в name
  File "C:\Users\vvash\Desktop\Urban University\Lessons_Urban\Module_12\module_12_4_1.py", line 6, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2025-01-31 10:20:53,277 | WARNING | Неверная скорость для Runner
Traceback (most recent call last):
  File "C:\Users\vvash\Desktop\Urban University\Lessons_Urban\Module_12\module_12_4_2.py", line 18, in test_walk
    runner = module_12_4_1.Runner("John", speed=-5)  # Передаем отрицательное значение в speed
  File "C:\Users\vvash\Desktop\Urban University\Lessons_Urban\Module_12\module_12_4_1.py", line 11, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5
